In [1]:
import sys
from elasticsearch import Elasticsearch
import json
import time
import sys
# from elasticsearch import Elasticsearch
# from elasticsearch.helpers import bulk
# import csv
import tensorflow as tf
# import tensorflow_hub as hub

ModuleNotFoundError: No module named 'tensorflow'

In [13]:
ELASTIC_SEARCH_BODY_FOR_DOCUMENTS={"mappings": {
    "properties": {
          "title": {
                "type": "text"
          },
          "title_vector": {
                "type": "dense_vector",
                "dims": 512
      }
  }
   }
 }
host_port_dict={
        'host': 'localhost', 
        'port': 9200,
        'scheme': "http"
        }

es=Elasticsearch([host_port_dict])
# d=ElasticSearchConnect(host_port_dict).create_index(index_name="questions_index", index_body=ELASTIC_SEARCH_BODY_FOR_DOCUMENTS )
# cursor=db.get_elastic_cursor()
if es.ping():
    print("connected")
else:
    print("not connected")

connected

In [25]:
es = Elasticsearch([{'host': 'localhost', 'port': 9200, 'scheme': "http"}])
if es.ping():
	print('Connected to ES!')
else:
	print('Could not connect!')
	sys.exit()

Connected to ES!

In [26]:
# index in ES = DB in an RDBMS
# Read each question and index into an index called questions
# Indexing only titles for this example to improve speed. In practice, its good to index CONCATENATE(title+body)
# Define the index


#Refer: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html
# Mapping: Structure of the index
# Property/Field: name and type  
b = {"mappings": {
  	"properties": {
    		"title": {
      			"type": "text"
    		},
    		"title_vector": {
      			"type": "dense_vector",
      			"dims": 512
		}
	}
     }
   }


ret = es.indices.create(index='questions-index', ignore=400, body=b) #400 caused by IndexAlreadyExistsException, 


# TRY this in browser: http://localhost:9200/questions-index

print("*********************************************************************************");

/var/folders/zn/4zzj_7js7351yjh2d0dss37h0000gn/T/ipykernel_90585/3010607707.py:24: DeprecationWarning: Passing transport options in the API method is deprecated. Use 'Elasticsearch.options()' instead.
  ret = es.indices.create(index='questions-index', ignore=400, body=b) #400 caused by IndexAlreadyExistsException,
/var/folders/zn/4zzj_7js7351yjh2d0dss37h0000gn/T/ipykernel_90585/3010607707.py:24: DeprecationWarning: The 'body' parameter is deprecated and will be removed in a future version. Instead use individual parameters.
  ret = es.indices.create(index='questions-index', ignore=400, body=b) #400 caused by IndexAlreadyExistsException,

TypeError: Object of type ObjectApiResponse is not JSON serializable

In [4]:
import json
import time
import sys

import csv



# CONSTANTS
NUM_QUESTIONS_INDEXED = 20000

# Col-Names: Id,OwnerUserId,CreationDate,ClosedDate,Score,Title,Body
cnt=0

f = open("top200KQuesData", "w", encoding="latin1")

with open('../data/raw_data/Questions.csv', encoding="latin1") as csvfile:
	readCSV = csv.reader(csvfile, delimiter=',' )
	next(readCSV, None)  # skip the headers
	for row in readCSV:
		#print(row[0], row[5])
		doc_id = row[0];
		title = row[5];

		# write to file
		f.write(doc_id+ "," +title+"\n")

		# keep count of # rows processed
		cnt += 1
		if cnt%100==0:
			print(cnt)

		if cnt == NUM_QUESTIONS_INDEXED:
			break;

	print("Completed indexing....")

	print("*********************************************************************************");

f.close()

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18500
18600
18700
18800
18900
19000
19100
19200
19300
19400
19500
19600
19700
19800
19900
20000
Completed indexing....
*********************************************************************************

In [5]:
import pandas as pd
df=pd.read_csv(r"../data/raw_data/Questions.csv", encoding='ISO-8859-1')

In [6]:
df.head()

,Id,OwnerUserId,CreationDate,ClosedDate,Score,Title,Body
0,80,26.0,2008-08-01T13:57:07Z,NaN,26,SQLStatement.execute() - multiple queries in o...,<p>I've written a database generation script i...
1,90,58.0,2008-08-01T14:41:24Z,2012-12-26T03:45:49Z,144,Good branching and merging tutorials for Torto...,<p>Are there any really good tutorials explain...
2,120,83.0,2008-08-01T15:50:08Z,NaN,21,ASP.NET Site Maps,<p>Has anyone got experience creating <strong>...
3,180,2089740.0,2008-08-01T18:42:19Z,NaN,53,Function for creating color wheels,<p>This is something I've pseudo-solved many t...
4,260,91.0,2008-08-01T23:22:08Z,NaN,49,Adding scripting functionality to .NET applica...,<p>I have a little game written in C#. It uses...

In [7]:
df=df.iloc[:20000]

In [8]:
df.head()

,Id,OwnerUserId,CreationDate,ClosedDate,Score,Title,Body
0,80,26.0,2008-08-01T13:57:07Z,NaN,26,SQLStatement.execute() - multiple queries in o...,<p>I've written a database generation script i...
1,90,58.0,2008-08-01T14:41:24Z,2012-12-26T03:45:49Z,144,Good branching and merging tutorials for Torto...,<p>Are there any really good tutorials explain...
2,120,83.0,2008-08-01T15:50:08Z,NaN,21,ASP.NET Site Maps,<p>Has anyone got experience creating <strong>...
3,180,2089740.0,2008-08-01T18:42:19Z,NaN,53,Function for creating color wheels,<p>This is something I've pseudo-solved many t...
4,260,91.0,2008-08-01T23:22:08Z,NaN,49,Adding scripting functionality to .NET applica...,<p>I have a little game written in C#. It uses...

In [11]:
df.to_json("questions20k.json", orient='records', indent=4)